### ISSUE TITLE
Sharded Redis

### ISSUE THREAD

**Issue by shmish111** [ptaoussanis/carmine#133]
I appreciate that this functionality would be superseded by Redis Cluster on Redis 3 but for those of us who will be using Redis < 3.0 for a while has anyone looked at implementing something like `ShardedJedis`?  If not, would a PR be accepted if I work on it?

**Comment by ptaoussanis** [comment]
Hi David,

Now that Cluster's officially out with Redis 3, other sharding approaches are basically obsolete.

For Cluster support - most of the hairy internals are already in Carmine to support Cluster in a way that works well with Carmine's own features (request pipelining and parsers, etc.). There's still some [work](https://github.com/ptaoussanis/carmine/issues/76) needed, and that'll definitely need to come from PR since I'm short on time lately and don't have any need for Cluster myself.

There's a [cluster ns](https://github.com/ptaoussanis/carmine/blob/master/src/taoensso/carmine/cluster.clj) with an old (+ possibly out-of-date) sketch of the work still needed. I'd suggest starting there if you or anyone else were interested in investigating a Cluster PR.

Cheers :-)

**Comment by ptaoussanis** [comment]
> I appreciate that this functionality would be superseded by Redis Cluster on Redis 3 but for those of us who will be using Redis < 3.0 for a while

Sorry, I somehow missed this context. Is there a specific reason you would be hesitant to switch to Redis 3? It's a non-breaking upgrade in the vast majority of cases I believe.

**Comment by shmish111** [comment]
Because going from our current Jedis wrapper with sharding to carmine and
redis cluster all in one go will be scary but I suppose it's probably for
the best.

**Comment by ptaoussanis** [comment]
Ahh, gotcha. Does Jedis have support for Cluster yet? Perhaps you could switch to Jedis+Cluster as a first step?

**Comment by shmish111** [comment]
Nope :(  Plus I do not like it or the wrapper we use (an old in-house one)
so I don't want to make our code even more dependent on it.

**Comment by ptaoussanis** [comment]
Closing this for now.
