### ISSUE TITLE
Disque support

### ISSUE THREAD

**Issue by ptaoussanis** [ptaoussanis/carmine#141]
https://github.com/antirez/disque

Haven't investigated this yet. May make sense to integrate support with Carmine directly, to create a separate independent library, or to create a separate library but share protocol internals with Carmine (most likely this 3rd option).

Will likely implement this myself at some point, but have my hands full atm and it's a bit of a low priority - so PRs welcome to get this started/moving.

**Comment by cammellos** [comment]
HI, 
I have started implementing the disque API https://github.com/cammellos/carmine , it's still very rough but PING/ADDJOB/GETJOB/ACKJOB should be working. I have made a fork for now but if it's ok with you I would create a separate repository ( keeping the commit history ) and finish implementing the rest of the commands. I haven't changed most of the internals so it would probably be quite easy to extract those in a separate library.
Let me know if it's ok with you.
Thanks for the library.
andrea

**Comment by ptaoussanis** [comment]
> Let me know if it's ok with you.

Hi Andrea, I'm sorry, I'm not sure I understand what you're asking exactly. You'd like to create a separate library based on Carmine, or you'd like to get your Disque support added to Carmine when it's ready?

Have been thinking about Disque support recently. My current thinking is that the best long-term solution may be to release a new Redis core/protocol library that can be shared by Carmine and then a separate Disque library.

Your fork could help move this along if it can help me see exactly what parts of Carmine you need. Does that make sense?

**Comment by cammellos** [comment]
Hi ,

Yes, that's what I meant, sorry if it wasn't clear,

I would like to create a separate library based on Carmine, and then
eventually have it using a shared Redis core/protocol library once it's
clear what it is using.

I am removing those parts of carmine that are not going to be used by a
separate disque library ( tundra for example, or all the backward
compatibility code ) for now, so that should make it easier to see what it
is been used by both components.

**Comment by ptaoussanis** [comment]
Closing as part of issue triage since work on Disque appears to have been abandoned.
