### ISSUE TITLE
Support for different serialization formats

### ISSUE THREAD

**Issue by whilo** [ptaoussanis/carmine#184]
Hi,

thanks for your great work! I have implemented a [first sketch of a carmine backend for konserve](https://github.com/replikativ/konserve/blob/master/src/konserve/carmine.clj), but I need flexible serialization and deserialization (I have added comments from the filestore backend for serialization). 

I can serialize and deserialize a bytearray coming from carmine as a workaround, but that means doing serialization again with nippy in carmine (bad solution). In carmine/protocol.clj there is a TODO for flexible serialization. I would propose to expose a dynamic binding for the parse and thaw routines or to use [incognito](https://github.com/replikativ/incognito) and expose the serializer instance through a binding. I would add nippy support for your needs then. Carmine would automatically gain support for other serializations like fressian and transit then.

I can also try to implement it myself, but I am not totally sure where I should expose the binding, as there are some defalias things and you have possibly some implicit dependencies on nippy as a serialization.

Best,
Christian

**Comment by ptaoussanis** [comment]
Hey Christian,

Haven't had a chance to look over this properly- but just wanted to throw out in case you weren't aware that Carmine supports raw arguments using [raw](https://github.com/ptaoussanis/carmine/blob/3f931ae7d64382ce417ee0ffeb393eacfb70c36e/src/taoensso/carmine/protocol.clj#L51) on writes, and [parse-raw](https://github.com/ptaoussanis/carmine/blob/3f931ae7d64382ce417ee0ffeb393eacfb70c36e/src/taoensso/carmine/protocol.clj#L241) on reads.

With these, you can use your own arbitrary de/serialization mechanism w/o going through Nippy.

Let me know if that's what you're looking for? Otherwise will try take a closer look at this issue next week.

Cheers, and good luck with the libs!

**Comment by whilo** [comment]
Thanks tha worked :).
