### ISSUE TITLE
Carmine connection seems to fail for 7.x redis - might be lack of support for SSL or "rediss:/" uri

### ISSUE THREAD

**Issue by Skiggz** [ptaoussanis/carmine#282]
URI format "rediss://" doesn't seem to be supported. Is it expected that these connections would fail? I'm trying to connect to a 7.0.x instance, whereas connecting to 6.2.x is fine. 

The only thing that is odd, is that I can't connect to 7.0.x even if I don't use TLS (change the uri to "redis:/") but I'm wondering if the server is rejecting that (it's hard to tell, the error just says connection reset). Trying to eliminate possibilities and wondering if carmine simply doesn't support this.

**Comment by ptaoussanis** [comment]
@Skiggz Hi Skylar, thanks for pinging about this!

"rediss://" URIs are definitely not supported, since I'd never seen them before ^^
Just added support to master now, will be included in the next release.

In the meantime (and actually in any case), I'd suggest using an explicit [config map](https://github.com/ptaoussanis/carmine/blob/8d58b715cfe738e345950fed5a93336f7757f508/src/taoensso/carmine.clj#L65) since these are a lot more flexible.

> The only thing that is odd, is that I can't connect to 7.0.x even if I don't use TLS (change the uri to "redis:/")

There's no reason that Carmine should have trouble connecting to Redis 7.x.
I'd recommend playing with the explicit config options linked above. In particular, I suspect you may need to include `:ssl-fn :default` in your connection config map. It's possible your Redis 7.x server is rejecting non-TLS connection attempts.

If that doesn't help, it might be worth also checking if there's been any changes in your Redis server's [ACL policy](https://redis.io/docs/management/security/acl/).

Feel free to ping if none of that was helpful. Cheers! :-)

**Comment by ptaoussanis** [comment]
Closing, this will addressed in forthcoming release 👍
