### ISSUE TITLE
wcar return result type is dependent on number of expressions in the body

### ISSUE THREAD

**Issue by alexkehayias** [ptaoussanis/carmine#80]
When using `wcar`, if you have a single `car/get` in the body, it will return the value of the key. If you have multiple `car/get` in the body, it will return a vector of values. I would expect it to return a vector in both cases. Redis `MULTI`/`EXEC` returns a list even if a single query is in the body. Is this expected behavior? Maybe an update to the readme if that's the case.

Looking at the source of `wcar` I noticed the `:as-pipeline` argument which returns the results I expected.

Using: `[com.taoensso/carmine "2.6.0"]`

Test case:

```
(ns my-ns.core
  (:require [taoensso.carmine :as car :refer (wcar)]))

(type (wcar {} (car/get "my-key"))
;; nil
(type (wcar {} (car/get "my-key") (car/get "my-key")))
;; clojure.lang.PersistentVector
(type (wcar {} :as-pipeline (car/get "my-key")))
;; clojure.lang.PersistentVector
(type (wcar {} :as-pipeline (car/get "my-key") (car/get "my-key")))
;; clojure.lang.PersistentVector
```

**Comment by gltronred** [comment]
When you have `wcar` that doesn't execute any commands, it returns `nil` even with `:as-pipeline` set.

Suppose that you map over vector with keys. If the vector with keys is non-empty, several queries are executed, and return value is a vector. But if the vector with keys is empty, there are no queries, and return value is just `nil`, not a vector anymore. I suppose that the correct behaviour should be returning `[]`:

```clojure
(let [keys0 []]
  (wcar :as-pipeline {} (mapv #(car/get %) keys0)))
;; nil
(let [keys1 ["somenonexistentkey"]]
  (wcar :as-pipeline {} (mapv #(car/get %) keys1)))
;; [nil]
(let [keys2 ["some" "nonexistentkey"]]
  (wcar :as-pipeline {} (mapv #(car/get %) keys2)))
;; [nil nil]
```

Am I missing something? Should I create a new issue for it?

P.S. It seems that here https://github.com/ptaoussanis/carmine/blob/master/src/taoensso/carmine/protocol.clj#L301 a number of commands sent to wcar is checked before than `:as-pipeline`.

**Comment by ptaoussanis** [comment]
Hi there,

>  I suppose that the correct behaviour should be returning []

The current behaviour is correct (intentional) in all your examples.

In the first case, no Redis command is run.
In the second, one command is run (with return value nil if the key isn't present).
In the third, two commands are run (with return values nil if the keys aren't present).

Empty seqs in Clojure are generally ~interchangeable with nil, and that tends to be a nice property. In this case, the point of `:as-pipeline` is that it (always) be safe for positional destructuring. That does remain the case when the return value is `nil`.

I.e. try think of the `:as-pipeline` contract like: return a destructurable result. The particulars beyond that shouldn't really matter.

Does that make sense? Is there something in particular you're trying to do that I could give an example for?

**Comment by gltronred** [comment]
Thank you for quick answer.

> Empty seqs in Clojure are generally ~interchangeable with nil

I think this is true for Common Lisp but not for Clojure, am I wrong? E.g. `(when [] 1)` is 1, but `(when nil 1)` is nil.

I return results from Redis to user, and it is not coherent to send a vector in some cases and `null` in other cases.

> In this case, the point of :as-pipeline is that it (always) be safe for positional destructuring

I do not understand what do you mean by "safe for positional destructuring". I tried to test it, but it returns the same results for me. Is it wrong for some other version of Clojure?

```clojure
(let [[h & t] nil] 
  {:h h :t t})
;; => {:h nil, :t nil}
(let [[h & t] []] 
  {:h h :t t})
;; => {:h nil, :t nil}
```

> I.e. try think of the :as-pipeline contract like: return a destructurable result. 

I thought that `:as-pipeline` returns a vector of results of commands, so if there are no commands, `:as-pipeline` should return empty vector. Apparently, this line in README is wrong:
> To always return a vector, add the `:as-pipeline` argument to `wcar`

Should it be fixed to something like this?
> With `:as-pipeline` argument `wcar` returns a vector, unless there are no commands, in which case it returns `nil`

**Comment by ptaoussanis** [comment]
Sorry for being terse, just a bit short on time atm.

> I think this is true for Common Lisp but not for Clojure, am I wrong? E.g. (when [] 1) is 1, but (when nil 1) is nil.

Concrete collections are truthy (e.g. []), but empty `seq`s are nil. `(seq []) => nil`, etc.

> I do not understand what do you mean by "safe for positional destructuring". I tried to test it, but it returns the same results for me.

What I mean is just that the result is safe for destructuring.

I.e. `(let [[x1 x2] (wcar {} ...)])` may or may not do what you're hoping it will (destructure values for `x1`, `x2`) - depending on how many Redis commands are actually called in the `wcar` body. E.g. if one `get` is called, then the `wcar` result could be a string, etc.

`(let [[x1 x2] (wcar :as-pipeline {} ...)])` will always destructure correctly because here the result of `wcar` will always be a vector, or nil.

> I tried to test it, but it returns the same results for me.

Yes, that's the idea: if you destructure nil or an empty vector, you get exactly the same result. In both cases your binding vals will be nil.

It's in that sense that I meant that empty seqs are nil. A positional destructure like `(let [[x1 x2] val)` will take a `seq` view of `val`. And `(= (seq []) nil)`.

> Apparently, this line in README is wrong

Technically yes, but not in an important way. For example, the fix you've proposed there would bring a lot of attention to what's inherently just not a very interesting property with any obvious applications.

A lot of API stuff in Clojure has similar nuanced behaviour at the edges when dealing with empty seqs, since the particular semantics are rarely super important in those cases. `mapv` will always return a vector, a lot of the seq API utils will return nil on an empty input, etc.

When you need/want particular semantics, you can reach for stuff like `(seq x)`, `(not-empty x`), `(when x)`, `(when (seq x))`, `(when-let [c (not-empty x)])`, `(or (not-empty x) [])`, etc., etc.

I usu. tend to prefer returning nil to empty collections when it makes sense since that's easier to test against in `when`s and the like, but it very much depends on what the API is for and what the most common uses will be.

In the case of `wcar`, just doesn't make much difference one way or the other since the no-command edge case isn't usually something you'd care about, and it doesn't affect the intended purpose of the `:as-pipleline` flag (destructuring safety). 

Hope that helps / makes sense?

**Comment by gltronred** [comment]
Thank you for such detailed explanation, I've got your point.

I'll leave a workaround here for those who also wants to get `[]` in such cases:
```clojure
(mapv identity (wcar ...))
; e.g.
(mapv identity (wcar {} (mapv #(car/get %) []))
;; => []
```

**Comment by ptaoussanis** [comment]
> I'll leave a workaround here for those who also wants to get [] in such cases:

Sorry, I'm not sure I'm following what your intention is with this. In any case, might instead suggest `(or (wcar ...) [])`.

Best of luck! :-)

**Comment by ptaoussanis** [comment]
@gltronred Have clarified the README docs a little- https://github.com/ptaoussanis/carmine#basic-commands
